### ISSUE TITLE
pyodide is trying to load it's WASM runtime from an invalid path

### ISSUE THREAD

**Issue by harabat** [YunoHost-Apps/n8n_ynh#189]
Creating Python code blocks leads to error:

```
Cannot find module '/var/www/n8n/file:/var/www/n8n/node_modules/src/js/pyodide.asm.js' imported from /var/www/n8n/node_modules/pyodide/pyodide.mjs
```

The issue is with upstream n8n, the fix was introduced in https://github.com/n8n-io/n8n/pull/14487, could n8n be updated to >=1.87.2?
